trydjango32/articles/urls.py
from django.urls import path

from .views import (
    article_search_view,
    article_create_view,
    article_detail_view
)

app_name = 'articles'
urlpatterns = [
    path('', article_search_view, name='search'),
    path('create/', article_create_view, name='create'),
    path('<slug:slug>/', article_detail_view, name='detail'),
]

trydjango32/src/urls.py
from django.contrib import admin
from django.urls import include,path
from accounts.views import login_view
from accounts.views import (
    login_view,
    logout_view,
    register_view
)
from articles.views import (
    article_search_view,
    article_create_view,
    article_detail_view
)
from articles import views
from .views import home_view

urlpatterns = [
  path('', home_view), # index / home / root 
  path('pantry/recipes/', include('recipes.urls')),
  path('articles/', include('articles.urls')),
  path('admin/', admin.site.urls),
  path('login/', login_view),
  path('logout/', logout_view),
  path('register/', register_view),
]

trydjango32/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>Document</title>
  <script src="https://unpkg.com/htmx.org@1.5.0"></script>
  <style>
    .htmx-indicator {
        display: none;
    }
    .htmx-request .htmx-indicator {
        display: inline;
    }
    .htmx-inverted-indicator {
        display: inline;
    }
    .htmx-request .htmx-inverted-indicator {
        display: none;
    }
</style>

</head>
<body>
  <h1>Hello World</h1>
  <form action='/articles/' method='GET'>
      <input type='text' name='q' />
      <input type='submit' />
  </form>

  {% block content %}
  <h3>This will be replaced</h3>
  {% endblock content %}

</body>
</html>

trydjango32/templates/home-view.html
{% extends "base.html" %}

{% block content %}
  <a href='{% url "articles:create" %}'>Create Article</a>
  <a href='{% url "articles:detail" slug="hello-world" %}'>Hello world article</a>
  <ul>
    {% for x in object_list %}
      {% if x.title %}
        <li>
          <a href="{{ x.get_absolute_url }}">{{ x.title }} - {{ x.content }}</a>
        </li>
      {% endif %}
    {% endfor %}
  </ul>
{% endblock content %} 